### ISSUE TITLE
Unable to import textures (DARK SOULS III)

### ISSUE THREAD

**Issue by phoondos** [FelixBenter/DCX-Blender#1]
I've tried multiple times to get the texture importing to work, but every single time the console tells me Texture file not found. I've tried naming the texture the exact same name with the partsbnd.dcx, I've tried just wp_a_0632, but I can't get it to recognize the dds files in the same directory. It is most likely user error but I think there should be more clarity on the instructions to get texture importing working.

**Comment by FelixBenter** [comment]
partbnd files were something I hadn't gotten around to support yet, so not a user error. Please try the most recent version now, seems to be working with DS3 and Sekiro files.
![image](https://user-images.githubusercontent.com/31024598/109906648-ff2dfb00-7cf4-11eb-9997-254f6549e796.png)

**Comment by phoondos** [comment]
thank you. also, certain partsbnd files don't import correctly because they have two flvers. I don't know if you know already, so I'm just putting it out there.
